name: composite
favicon: null
layout_spectrum: 0.6469202740117908
typography_spectrum: 0.8254157283809036
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3010711788665503
  lightness: 0.540222478331998
  saturation: 0.28852765867486596
  rhythmicContrast: 0.04132451699115336
purpose: []
